# Generated by Django 5.1.15 on 2026-04-18 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Copil', 'verbose_name_plural': 'Copii'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['child', 'name'], 'verbose_name': 'Document', 'verbose_name_plural': 'Documente'},
        ),
        migrations.AlterModelOptions(
            name='parent',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Părinte', 'verbose_name_plural': 'Părinți'},
        ),
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Terapeut', 'verbose_name_plural': 'Terapeuți'},
        ),
        migrations.AlterModelOptions(
            name='therapy',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Ședință de terapie', 'verbose_name_plural': 'Ședințe de terapie'},
        ),
        migrations.RemoveField(
            model_name='therapy',
            name='duration',
        ),
        migrations.AddField(
            model_name='child',
            name='cnp',
            field=models.CharField(default='', help_text='13 cifre – vârsta și tipul (minor/major) se calculează automat.', max_length=13, verbose_name='CNP'),
        ),
        migrations.AddField(
            model_name='child',
            name='status',
            field=models.CharField(choices=[('activ', 'Activ'), ('arhivat', 'Arhivat')], default='activ', max_length=10, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='child',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Vârstă'),
        ),
        migrations.AlterField(
            model_name='child',
            name='child_type',
            field=models.CharField(choices=[('underage', 'Minor'), ('overage', 'Major')], default='underage', max_length=10, verbose_name='Tip'),
        ),
        migrations.AlterField(
            model_name='child',
            name='diagnostic',
            field=models.CharField(blank=True, choices=[('F84', 'F84'), ('349', '349')], default='', max_length=10, verbose_name='Diagnostic'),
        ),
        migrations.AlterField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.parent', verbose_name='Părinte'),
        ),
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(choices=[('male', 'Masculin'), ('female', 'Feminin')], max_length=10, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='document',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.child', verbose_name='Copil'),
        ),
        migrations.AlterField(
            model_name='document',
            name='creation_date',
            field=models.DateField(blank=True, help_text='Se completează când documentul este furnizat (Există = Da).', null=True, verbose_name='Dată creare'),
        ),
        migrations.AlterField(
            model_name='document',
            name='exists',
            field=models.BooleanField(default=False, help_text='A fost furnizat acest document?', verbose_name='Există'),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Poate fi resetată oricând.', null=True, verbose_name='Dată expirare'),
        ),
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='ex: "Certificat de naștere", "Raport medical"', max_length=200, verbose_name='Nume document'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(max_length=30, verbose_name='Număr de telefon'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='first_name',
            field=models.CharField(max_length=100, verbose_name='Prenume'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='last_name',
            field=models.CharField(max_length=100, verbose_name='Nume'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapies', to='core.child', verbose_name='Copil'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='date',
            field=models.DateField(verbose_name='Dată'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='start_time',
            field=models.TimeField(verbose_name='Oră start'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='therapist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapies', to='core.therapist', verbose_name='Terapeut'),
        ),
    ]
