# Generated by Django 5.1.15 on 2026-04-18 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_child_options_alter_document_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='cnp',
            field=models.CharField(default='', help_text='13 cifre – vârsta și tipul (minor/major) se calculează automat.', max_length=13, unique=True, verbose_name='CNP'),
        ),
    ]
