# Generated by Django 5.1.15 on 2026-04-18 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_child_cnp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='diagnostic',
            field=models.CharField(choices=[('F84', 'F84'), ('349', '349')], default='', max_length=10, verbose_name='Diagnostic'),
        ),
    ]
