# Generated by Django 5.1.15 on 2026-04-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_child_diagnostic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='sex',
            field=models.CharField(blank=True, choices=[('male', 'Masculin'), ('female', 'Feminin')], default='', max_length=10, verbose_name='Sex'),
        ),
    ]
