# Generated by Django 5.1.15 on 2026-06-17 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sex_blank_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='child',
            options={'ordering': ['last_name', 'first_name'], 'verbose_name': 'Pacient', 'verbose_name_plural': 'Pacienți'},
        ),
        migrations.AlterField(
            model_name='document',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.child', verbose_name='Pacient'),
        ),
        migrations.AlterField(
            model_name='therapy',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='therapies', to='core.child', verbose_name='Pacient'),
        ),
    ]
