# Generated by Django 5.1.15 on 2026-06-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_pacient_rename_nameorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parent',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=30, verbose_name='Număr de telefon'),
        ),
    ]
