# Generated by Django 5.1.15 on 2026-06-17 11:48

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_parent_phone_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.parent', verbose_name='Părinte'),
        ),
        migrations.CreateModel(
            name='TherapistDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nume document')),
                ('has_expiry', models.BooleanField(default=False, verbose_name='Are dată de expirare')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Dată expirare')),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to=core.models._therapist_doc_upload_path, verbose_name='Fișier PDF')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility_documents', to='core.therapist', verbose_name='Terapeut')),
            ],
            options={
                'verbose_name': 'Document eligibilitate psiholog',
                'verbose_name_plural': 'Documente eligibilitate psiholog',
                'ordering': ['therapist', 'name'],
            },
        ),
    ]
