# Generated by Django 5.1.15 on 2026-06-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_therapist_doc_parent_optional'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['child', 'name'], 'verbose_name': 'Document pacient', 'verbose_name_plural': 'Documente pacienți'},
        ),
    ]
