# Generated by Django 5.1.15 on 2026-07-09 13:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_document_pacient_rename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Centru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nume')),
            ],
            options={
                'verbose_name': 'Centru',
                'verbose_name_plural': 'Centre',
            },
        ),
        migrations.AddField(
            model_name='therapist',
            name='centru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='therapists', to='core.centru', verbose_name='Centru'),
        ),
    ]
