# Generated by Django 5.1.15 on 2026-07-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_centru_therapist_centru'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='has_expiry',
            field=models.BooleanField(default=True, verbose_name='Are dată de expirare'),
        ),
    ]
