# Generated by Django 5.1.15 on 2026-07-13 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_document_has_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapy',
            name='centru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='therapies', to='core.centru', verbose_name='Centru (snapshot)'),
        ),
    ]
