# Generated by Django 5.1.15 on 2026-07-13 14:30

from django.db import migrations, models
import django.db.models.deletion


def create_carpatex_and_assign(apps, schema_editor):
    """Create Carpatex centre if not exists, assign all null-centru therapists to it."""
    Centru = apps.get_model('core', 'Centru')
    Therapist = apps.get_model('core', 'Therapist')
    
    # Create Carpatex if not exists
    carpatex, created = Centru.objects.get_or_create(name='Carpatex')
    
    # Assign all therapists with null centru to Carpatex
    Therapist.objects.filter(centru__isnull=True).update(centru=carpatex)


def reverse_func(apps, schema_editor):
    """Reverse: set therapists with Carpatex centru back to null."""
    Centru = apps.get_model('core', 'Centru')
    Therapist = apps.get_model('core', 'Therapist')
    
    try:
        carpatex = Centru.objects.get(name='Carpatex')
        Therapist.objects.filter(centru=carpatex).update(centru=None)
    except Centru.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_backfill_therapy_centru'),
    ]

    operations = [
        migrations.RunPython(create_carpatex_and_assign, reverse_func),
        migrations.AlterField(
            model_name='therapist',
            name='centru',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='therapists', to='core.centru', verbose_name='Centru'),
        ),
    ]
