# Generated by Django 5.1.15 on 2026-07-13 14:56

from django.db import migrations, models


def create_initial_pret(apps, schema_editor):
    """Create initial standard therapy rate."""
    Pret = apps.get_model('core', 'Pret')
    Pret.objects.create(
        name="Taxa terapie standard",
        valoare=135,
        editable=False,
    )


def reverse_func(apps, schema_editor):
    """Reverse: delete initial pret."""
    Pret = apps.get_model('core', 'Pret')
    Pret.objects.filter(name="Taxa terapie standard").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_therapist_mandatory_centru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pret',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nume')),
                ('valoare', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valoare')),
                ('editable', models.BooleanField(default=True, help_text='Dacă False, acest preț nu poate fi editat/șters (e folosit de rapoarte).', verbose_name='Editabil')),
            ],
            options={
                'verbose_name': 'Preț',
                'verbose_name_plural': 'Prețuri',
            },
        ),
        migrations.RunPython(create_initial_pret, reverse_func),
    ]
