# Generated by Django 5.1.15 on 2026-07-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_pret_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pret',
            name='valoare',
            field=models.IntegerField(verbose_name='Valoare'),
        ),
    ]
